import "./globals.css";
import "@radix-ui/themes/styles.css";

import { Theme } from "@radix-ui/themes";

import type { Metadata } from "next";




/* FONTS TODO */
//// Google Fonts' Inter is slightly broken
//import localFont from "next/font/local";
//import { IBM_Plex_Mono } from "next/font/google";
//
//const sans = localFont({
//  src: [
//    { path: "./fonts/InterVariable.ttf", style: "normal" },
//    { path: "./fonts/InterVariable-Italic.ttf", style: "italic" },
//  ],
//  display: "swap",
//  variable: "--font-inter",
//});
//
//const mono = IBM_Plex_Mono({
//  weight: ["300"],
//  subsets: ["latin"],
//  display: "swap",
//  variable: "--font-plex-mono",
//});




/* METADATA TODO */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`antialiased` /* add font variables here */}>
      <body className="">
        {/* HEADER */}
        <main className="">
          <Theme>
            {children}
          </Theme>
        </main>
        {/* FOOTER */}
      </body>
    </html>
  );
}
